apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patchesStrategicMerge:
  - ./clair.deployment.patch.yaml
  - ./clair-pg-scale-up.patch.yaml
  - ./clair.deployment-scale-up.patch.yaml
components:
  - ../base
